name = "SplittablesBase"
uuid = "171d559e-b47b-412a-8079-5efa626c420e"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.1.15"

[deps]
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Setfield = "0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 1.0"
julia = "1"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
SplittablesTesting = "3bda5eb5-c32a-4f64-8618-df3be8968470"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Documenter", "OffsetArrays", "SplittablesTesting", "Test"]
